In [16]:
ownerpath = f'/Users/mia/Desktop/AST443 Observational Techniques in Astronomy'

In [17]:
import numpy as np
from astropy.io import fits
import glob

In [18]:
dark_frame = []
for i in range(10):
    filename = f'{ownerpath}/Lab 2/Darks/HAT_P_16_VISIBLE_DARK_20S_.0000000{i}.DARK.FIT'
    dark_f = fits.getdata(filename)
    dark_frame.append(dark_f)

In [19]:
dark_frame

[array([[1058, 1028, 1072, ...,  999, 1018,  996],
        [1047, 1038, 1023, ..., 1018, 1088, 1013],
        [1044, 1040, 1031, ..., 1010, 1019, 1033],
        ...,
        [1044, 1039, 1019, ..., 1023, 1034, 1023],
        [1047, 1038, 1035, ..., 1035, 1026, 1019],
        [1046, 1035, 1030, ..., 1024, 1018, 1017]], dtype=uint16),
 array([[1040, 1031, 1029, ..., 1012, 1006, 1013],
        [1063, 1037, 1051, ..., 1028, 1098, 1017],
        [1041, 1030, 1037, ..., 1014, 1029, 1029],
        ...,
        [1032, 1025, 1020, ..., 1030, 1025, 1019],
        [1039, 1031, 1031, ..., 1015, 1024, 1019],
        [1022, 1029, 1026, ..., 1026, 1011, 1030]], dtype=uint16),
 array([[1049, 1034, 1036, ..., 1001, 1022, 1009],
        [1050, 1039, 1051, ..., 1017, 1093, 1008],
        [1054, 1040, 1042, ..., 1018, 1022, 1024],
        ...,
        [1023, 1026, 1041, ..., 1019, 1030, 1014],
        [1042, 1020, 1043, ..., 1027, 1012, 1023],
        [1020, 1036, 1034, ..., 1020, 1011, 1023]], dtype=uint

In [20]:
master_dark_data = np.median(dark_frame, axis=0)

In [50]:
master_dark_data.shape

(1024, 1024)

In [22]:
file_flat2s = f'{ownerpath}/Lab 1 CCD/Group 5 data lab1/Photometry/Flats/flat_0C_2s_visible_.00000000.FLAT.FIT'
flat2s_0= fits.open(file_flat2s)

In [24]:
flat30 = [flat2s_0]
for i in range(9):
    filename = f'{ownerpath}/Lab 1 CCD/Group 5 data lab1/Photometry/Flats/flat_0C_30s_visible_.0000000{i+1}.FLAT.FIT'
    element = fits.open(filename)
    flat30.append(element)

In [27]:
def get_fits_data(filenames):
    data = []
    for filename in filenames:
        with fits.open(filename) as hdul:
            data.append(hdul[0].data)
    return np.array(data)

# List of flat-field files
flat_files = [f'{ownerpath}/Lab 1 CCD/Group 5 data lab1/Photometry/Flats/flat_0C_2s_visible_.00000000.FLAT.FIT']
for i in range(9):
    filename_flat_files = f'{ownerpath}/Lab 1 CCD/Group 5 data lab1/Photometry/Flats/flat_0C_30s_visible_.0000000{i+1}.FLAT.FIT'
    flat_files.append(filename_flat_files)

# Load flat-field data
flat_data = get_fits_data(flat_files)

# Compute the median flat field
master_flat = np.median(flat_data, axis=0)

#normalization
master_flat_normalized = master_flat / np.median(master_flat)

In [29]:
master_flat_normalized

array([[0.85989006, 0.87179422, 0.87161553, ..., 0.88027774, 0.88152006,
        0.87270469],
       [0.96986947, 0.9806249 , 0.9774255 , ..., 0.99723456, 0.99594119,
        0.98762785],
       [0.97730638, 0.97840404, 0.98307551, ..., 0.99451167, 0.99458825,
        0.98341587],
       ...,
       [0.94968602, 0.96775923, 0.96893348, ..., 0.95034972, 0.95269822,
        0.94133864],
       [0.95069008, 0.96443219, 0.96752948, ..., 0.95633158, 0.95612736,
        0.94322765],
       [0.95084325, 0.96699341, 0.96968227, ..., 0.95537006, 0.95199197,
        0.94161944]])

In [34]:
output_path = f'{ownerpath}/Lab 2'
master_flat_hdu = fits.PrimaryHDU(master_flat_normalized)
master_flat_hdu.writeto(f"{output_path}/master_flat.fits", overwrite=True)

In [46]:
science_files = []

for i in range(194):
    if i < 10:
        #print(f'HAT_P_16_VISIBLE_LIGHT_20S_.0000000{i}')
        filename = f'{ownerpath}/Lab 2/Transient/HAT_P_16_VISIBLE_LIGHT_20S_.0000000{i}.FIT'
    elif i < 100 :
        #print(f'HAT_P_16_VISIBLE_LIGHT_20S_.000000{i}')
        filename = f'{ownerpath}/Lab 2/Transient/HAT_P_16_VISIBLE_LIGHT_20S_.000000{i}.FIT'
    else:
        #print(f'HAT_P_16_VISIBLE_LIGHT_20S_.00000{i}')
        filename = f'{ownerpath}/Lab 2/Transient/HAT_P_16_VISIBLE_LIGHT_20S_.00000{i}.FIT'
    science_data = fits.getdata(filename)
    science_files.append(science_data)

In [54]:
science_data.shape

(1024, 1024)

In [56]:
science_files

[array([[1239, 1253, 1252, ..., 1205, 1216, 1238],
        [1276, 1258, 1262, ..., 1256, 1316, 1239],
        [1251, 1258, 1245, ..., 1240, 1245, 1267],
        ...,
        [1259, 1240, 1201, ..., 1220, 1233, 1205],
        [1255, 1236, 1254, ..., 1235, 1213, 1228],
        [1237, 1261, 1265, ..., 1231, 1232, 1228]], dtype=uint16),
 array([[1257, 1227, 1256, ..., 1202, 1223, 1201],
        [1273, 1248, 1262, ..., 1251, 1319, 1229],
        [1262, 1252, 1254, ..., 1218, 1228, 1252],
        ...,
        [1256, 1259, 1239, ..., 1233, 1235, 1222],
        [1262, 1242, 1244, ..., 1244, 1232, 1215],
        [1229, 1265, 1243, ..., 1224, 1245, 1225]], dtype=uint16),
 array([[1264, 1227, 1251, ..., 1206, 1211, 1191],
        [1288, 1258, 1254, ..., 1238, 1319, 1213],
        [1247, 1269, 1253, ..., 1232, 1228, 1265],
        ...,
        [1250, 1250, 1223, ..., 1224, 1235, 1234],
        [1235, 1225, 1266, ..., 1217, 1210, 1227],
        [1251, 1228, 1227, ..., 1247, 1212, 1221]], dtype=uint

In [55]:
calibrated_science = []
for science_file in science_files:
    corrected_data = science_file - master_dark_data
    calibrated_data = corrected_data * master_flat_normalized
    calibrated_science.append(calibrated_data)

In [57]:
calibrated_science

[array([[166.81867225, 189.61524225, 185.65410732, ..., 173.41471384,
         177.62629125, 196.35855414],
        [219.67543524, 216.71810384, 223.83044026, ..., 240.83214632,
         225.58067851, 225.67296336],
        [199.37050084, 213.7812835 , 209.39508347, ..., 224.26238066,
         224.27964977, 231.1027297 ],
        ...,
        [211.77998162, 200.32616021, 172.95462552, ..., 191.97064379,
         201.01932404, 176.03032624],
        [205.82440309, 196.26195095, 214.30778067, ..., 205.13312401,
         185.4887085 , 196.19135141],
        [192.07033577, 226.27645888, 224.96628716, ..., 200.62771226,
         204.20227702, 193.97360494]]),
 array([[182.29669339, 166.9485926 , 189.14056943, ..., 170.77388064,
         183.79693164, 164.0684808 ],
        [216.76582682, 206.9118548 , 223.83044026, ..., 235.84597352,
         228.56850207, 215.79668488],
        [210.12087099, 207.91085924, 218.24276306, ..., 202.38312401,
         207.37164956, 216.35149164],
        ...,
